### ISSUE TITLE
APCA Contrast Calculator is broken

### ISSUE THREAD

**Issue by kazerniel** [Myndex/SAPC-APCA#118] opened 2024-05-27 16:07 UTC
**Does this relate to a web app or tool (i.e. you're an end user) OR is this about code or code integration (you're a developer).**
end user of https://www.myndex.com/APCA/

**Describe the bug**
web app is broken, the UI is empty

**To Reproduce**
Steps so we can reproduce the behavior:
Visit https://www.myndex.com/APCA/

**Screenshots**
![image](https://github.com/Myndex/apca-w3/assets/5689996/2c1b40a7-7553-472a-b611-d8fd0b75c7dd)

**System or device information (please complete the following):**
- Device: Desktop
- OS: Windows 10
- Browser: both Firefox 126.0 and Chromium 124.0.6367.201

**Additional context**
It broke sometime in the last 1-2 weeks.

**Comment by electrovir** [comment] 2024-05-27 16:56
Is the source code for this page available somewhere? I tried to find it to test which commit broke it but I can't find it anywhere. I assume it's private then.

**Comment by Myndex** [comment] 2024-05-27 21:39
Hi @kazerniel and @electrovir 

It is working fine for us on MacOS, in Safari (16.6.1 (16615.3.12.11.5, 16615)), as well as Chrome (125.0.6422.113) and the latest Firefox (126.0 64-bit) on MacOS. No issues, no errors.


> _"...I tried to find it to test which commit broke it ..."_

The page as served has not changed in _any_ way since June 2023, and the main JS script hasn't changed since May 2022, literally two years ago.

Soooo.... can you look in the JS console of the browser and see if there are any errors? I don't have a Windows 10 machine within reach at the moment.

Was there a recent Windows update? Is the issue also in Opera and Edge?


> _"...Is the source code for this page available somewhere?..."_

It's plain vanilla JS, not compiled, easy to view with plenty of comments, using the Browser's dev tools.


Thanks for bringing this to our attention, we'll look into it further. A console log if you get a chance would be extremely helpful.

Thank you!

**Comment by electrovir** [comment] 2024-05-27 22:47
macOS 14.5 here
- Safari 17.5
- Fierfox 126.0
- Chrome 125.0

All three browsers experience the same behavior:

1. Type in a color
2. `INVALID COLOR` is shown while mid-typing
3. `INVALID COLOR` never goes away
4. the page never updates in any way beyond updating the color swatch

(I'd also note that there are scrollbars in a weird place.)

![safari](https://github.com/Myndex/SAPC-APCA/assets/1205860/2929ebed-64be-4357-8f3f-ed7800e18aef)

I tried with `#000000`, `000000`, and `black`. None work.

I see the following logs:
- [Log] colorParsley error: unable to parse string (colorparsley.js, line 308)
- [Error] ReferenceError: Can't find variable: testContrast
	entryKeys (APCA:396)
	onkeyup (APCA:492)
- [Error] ReferenceError: Can't find variable: sliderPickerTXT
	getCSScolor (APCA:196)
	entryKeys (APCA:395)
	onkeyup (APCA:492)
- [Error] ReferenceError: Can't find variable: sliderPicker
	getCSScolor (APCA:169)
	getColorURL (APCA:345)
	onload (APCA:454)

Each of those is repeated multiple times.

**Comment by Myndex** [comment] 2024-05-28 01:35
Hi @electrovir 

Thank you—this is puzzling.

`testContrast()`, `sliderPickerTXT()`, and `sliderPicker()` are function calls, defined in a script after the `</body>` tag. This implies that the whole page is not loading, or that a dependent script is not loading.

Can you look at sources by type, and see that these JS scripts are loaded?

![List of loaded scripts in the APCA tool](https://github.com/Myndex/SAPC-APCA/assets/42009457/6aa05456-54b7-4625-b3be-6e1a34aab4c4)

Do you have any blockers? 

I was able to reproduce by going through a VPN that for some reason was preventing the Google analytics script from loading.

I'll assume that is the fail, but OMG not loading an async script should not bring down the whole page...! _(Thanks Google....)_

Working on a fix... Open to ideas...

**Comment by electrovir** [comment] 2024-05-28 01:55
Ah! That explains it. My firewall blocks Google tag manager 😁

I’ve fixed a similar situation before by sticking the script into an iframe. That wasn’t for Google tag manager though, so I don’t have insight into whether an iframe would mess the script up.

**Comment by Myndex** [comment] 2024-05-28 03:52
Hi @electrovir @kazerniel 

Well, it wasn't tag manager... it was something else ~ _yukky_ ~, that has to do with this page developing a greater popularity that I anticipated for what was intended as a non-production demonstrator... LOL!

Should be fixed now, and THANK YOU BOTH so very much for bringing this to my attention. The very narrow specific failure mode here meant that we would not have noticed it on our local network.

We are working on an upgrade, and intend to deploy on production servers in the near future—this just puts some fire under my butt to complete that sooner than later.


Thank you again!

**Closed by Myndex** 2024-05-28 03:52 UTC
Labels: bug, User Interface, Tool Features
