### ISSUE TITLE
Having trouble understanding the results

### ISSUE THREAD

**Issue by fstrr** [Myndex/SAPC-APCA#7] opened 2020-11-03 21:32 UTC
Hi

This is feedback on the beta version that was demoed on the Silver call on November 3rd. I've put a couple of values into the tool (#00c7fd and #ffffff) and am trying to make sense of the results.

![a screenshot of the SAPC tool showing the results of comparing a light-blue background against white text](https://user-images.githubusercontent.com/20049493/98042642-c3336980-1dd8-11eb-93cc-935978a87231.png)

If I look at the Font Weight 400 column, these are the results:

| Score | Result | 
|--------|:------:|
| Preferred | ⊘ |
| Score 4 | 101px |
| Score 3 | 89px |
| Score 2 | 75 |
| Score 1 | 63 | 

My assumption is that:

1. These two colors have poor contrast so there's no preferred size and weight, hence the ⊘ symbol.
2. If I want Score 4 conformance, my computed font size at 400 weight has to be at least 101px.
3. If I want Score 3 conformance, my computed font size at 400 weight has to be at least 89px.

After that is where I get confused. What do the 75 and 63 values refer to? I'm assuming it's not computed text size because "px" is missing. Is the reason those values are displayed in my chosen colors and in larger sizes relevant?

Thanks.

**Comment by Myndex** [comment] 2020-11-04 02:50
Hi @fstrr Francis, thank you for commenting.

### All values are font size in px. 

Sorry if I wasn't clear on that, I'll add a statement at the top to clarify.

- Fonts about 81px and smaller are shown at the actual weight and size using the actual colors chosen.

- Fonts larger than 81px are all shown at 24px and against white because they do not fit in the example boxes.

- Fonts about 81px and smaller fit in the example boxes, but fonts larger than 36px do not fit unless px is removed, so fonts  between 36 and 81 are shown just as the size figure.

**PREFERRED:** At the moment I am cutting off preferred at 56%. This is not set in stone.

### On Your Example

Your example uses a fairly saturated hue. I'm comparing that below with a sample at the same contrast, but with no hue or saturation. 
![Screen Shot 2020-11-03 at 5 37 17 PM](https://user-images.githubusercontent.com/42009457/98059343-b70cd380-1dfb-11eb-8841-1ec2957147c7.png)

If you find the blue sample seems more vibrant and contrasty, it's because the hue and saturation contrast is being added to the overall contrast perception.

## BUT
Contrast perception that includes hue and saturation is not helpful for determining **readability contrast**, which is our goal. Some hue and saturation combinations interfere with readability and some impairments. Also, color hue/saturation/chroma has a lower resolution and lower effect on contrast than luminance. 

For readability, which I mean is the fluent reading at best speed, where whole words and letter pairs are recognized by the VWFA (Visual Word Form Area) we want a very high luminance contrast.

This has been known for hundreds of years in the schools of classical design, but has been lost in the last 12 years of too-thin fonts and too-grey colors.

### Additional Discussion
In your examples, the contrast is high enough that the subtle difference may not be obvious, so here's another:

![Screen Shot 2020-11-03 at 6 06 12 PM](https://user-images.githubusercontent.com/42009457/98060981-c8f07580-1dff-11eb-8166-1e5f7eaeb493.png)
![Screen Shot 2020-11-03 at 6 08 44 PM](https://user-images.githubusercontent.com/42009457/98060999-cdb52980-1dff-11eb-8142-f32647788b73.png)

Both calculate as the same luminance, but the top one "seems" more contrasty due to the high saturation difference. But what is important is the luminance contrast, which is barely passable (these pass level 1 and 2 only, and even then only with these clown-sized fonts).

We are at the legibility level. Look at these colors with small thin fonts:

![Screen Shot 2020-11-03 at 6 32 36 PM](https://user-images.githubusercontent.com/42009457/98062546-1de1bb00-1e03-11eb-97fd-b16beec80bac.png)
![Screen Shot 2020-11-03 at 6 31 41 PM](https://user-images.githubusercontent.com/42009457/98062553-21754200-1e03-11eb-833e-33ead558f201.png)

Can you make them out? Sure you probably CAN, by going letter by letter and exerting a lot of effort. That's legibility. If you have young eyes, between the ages of 20 and 40, with good acuity, you might even be able to read them close to full speed. I definitely can not, even with glasses.

Hence, you can not really "judge by eye" what makes for good _readability_ contrast.

**The VISUAL CONTRAST / READABILITY spec is about READABILITY not legibility.**

It should be noted that there are known problems with the CIE's XYZ and other color spaces, which do have a very minor effect on luminance calculations, nevertheless the critical importance of luminance contrast for readability over chroma/hue is fairly well understood. 

OBJECT RECOGNITION is a different matter, and processed differently. Look for _"Visual Contrast Object and Non-Text"_ in the near future.

Andy

**Comment by Myndex** [comment] 2021-10-31 11:08
This was fixed in the Jan 2021 revision, answer is useful for the FAQ, but the issue is closed now. Thank you.

**Closed by Myndex** 2021-10-31 11:08 UTC
Labels: documentation, question, Theory, User Interface, Possible FAQ Entry
